// Dimension: apiFidelity (weight .25)
// Checks that (a) every design-system component the agent uses actually
// exists in the extracted catalog (hallucination), and (b) every prop it
// passes to a component is a real prop of that component (invention).
//
// "Uses" means two different things depending on SystemConfig.componentModel.
// The default 'react' model is import-anchored: a JSX element counts as
// design-system usage only once an import from componentsPkg binds its name,
// which is what makes local aliasing (`import { Button as Btn }`) resolve
// correctly and keeps a plain `<button>` from being mistaken for the system's
// `<Button>`. A 'custom-elements' system has no such anchor — the elements are
// registered once by the app entry point and then written as bare tags — so
// import-anchored detection would score a flawless answer as "no design-system
// components used", zero, hard fail. For those systems a JSX tag is resolved
// straight against the catalog by name.
//
// That name must contain a dash. A dash is what the custom-element spec
// requires of an element, so it is also what makes tag resolution safe: it
// cannot collide with a native HTML element, and it cannot collide with a
// component the agent defined locally. Resolving against allExports alone is
// not safe, because allExports deliberately carries more than tags — the
// stencil strategy adds the PascalCase class-name spelling of every element,
// and the barrel walk merges in runtime helpers and re-exported types. Without
// the dash test, an agent's own local `<DsButton>` (or a hallucinated one, with
// no import at all) would be graded as system usage against that element's
// props. renderCustomElementTypes applies the same rule when it decides what
// to declare as a JSX intrinsic, so the grader and the compiler agree on what
// counts as an element.
//
// When the system config declares `contamination` sentinels (only meaningful
// when benchmarking more than one system side by side), this dimension also
// tags cross-system contamination: prop names or typography-utility casing
// that belong to another configured system.

import type { DimensionResult, Diff, Gate } from '../../types.ts';
import type { GradeContext } from '../context.ts';

// catalog.allPropsByExport is generated by react-docgen-typescript, which
// only sees props declared directly on the component's own prop type. Design
// system components spread `...rest` onto a native DOM element
// (React.ComponentProps intersections), so a docgen miss on these specific
// patterns does NOT mean the prop is invented — it means docgen didn't (and
// can't cheaply) enumerate the full DOM prop surface. We allow them through
// explicitly instead.
const ALWAYS_ALLOWED_ATTRS = new Set(['key', 'ref', 'children', 'className', 'style', 'id']);
// Standard HTML/DOM + React attributes that legitimately pass through a
// component's `React.ComponentProps<element>` intersections. A prop on this
// list is never "invented" — if it were genuinely invalid for the element,
// the compile dimension (tsc against the system's source types) catches it instead.
const DOM_PASSTHROUGH_ATTRS = new Set([
  // global
  'title', 'role', 'tabIndex', 'hidden', 'lang', 'dir', 'slot', 'translate', 'draggable',
  'contentEditable', 'spellCheck', 'inputMode', 'accessKey', 'autoCapitalize', 'autoCorrect',
  // forms & inputs
  'name', 'value', 'defaultValue', 'checked', 'defaultChecked', 'type', 'disabled', 'required',
  'readOnly', 'placeholder', 'autoComplete', 'autoFocus', 'form', 'min', 'max', 'minLength',
  'maxLength', 'step', 'pattern', 'multiple', 'accept', 'size', 'rows', 'cols', 'wrap',
  'list', 'selected', 'htmlFor', 'action', 'method', 'encType', 'noValidate', 'capture',
  // links & media
  'href', 'target', 'rel', 'download', 'src', 'srcSet', 'sizes', 'alt', 'loading', 'decoding',
  'crossOrigin', 'referrerPolicy', 'width', 'height', 'poster', 'controls', 'autoPlay', 'loop',
  'muted', 'playsInline', 'preload',
  // tables & misc structure
  'colSpan', 'rowSpan', 'scope', 'headers', 'open', 'reversed', 'start', 'dateTime', 'cite',
]);
const DATA_ATTR_RE = /^data-/;
const ARIA_ATTR_RE = /^aria-/;
const EVENT_HANDLER_RE = /^on[A-Z]/;

// The HTML spellings of className/htmlFor. React 19 passes both straight
// through on a custom element, unlike a native one where it tells you to use
// the React name, and a web-component system's documentation is HTML, so its
// examples teach these. Kept in step with UNIVERSAL_ELEMENT_ATTRS in
// src/run/fixture.ts, which declares the same two on every generated element.
const CUSTOM_ELEMENT_ATTRS = new Set(['class', 'for']);

function isAttrAllowed(attr: string, componentProps: string[], customElements: boolean): boolean {
  if (componentProps.includes(attr)) return true;
  if (ALWAYS_ALLOWED_ATTRS.has(attr)) return true;
  if (customElements && CUSTOM_ELEMENT_ATTRS.has(attr)) return true;
  if (DOM_PASSTHROUGH_ATTRS.has(attr)) return true;
  if (DATA_ATTR_RE.test(attr)) return true;
  if (ARIA_ATTR_RE.test(attr)) return true;
  if (EVENT_HANDLER_RE.test(attr)) return true;
  return false;
}

function matchesPkg(source: string, pkg: string): boolean {
  return source === pkg || source.startsWith(`${pkg}/`);
}

// Derive the "family" prefixes (e.g. "body", "heading") present in this
// system's own typography utilities, so we can build a regex that catches
// the same families spelled in another configured system's casing convention.
function typographyPrefixes(utilities: string[], style: 'camel' | 'kebab'): string[] {
  const prefixes = new Set<string>();
  for (const u of utilities) {
    if (style === 'camel') {
      const m = /^([a-z]+)[A-Z]/.exec(u);
      if (m) prefixes.add(m[1]);
    } else {
      const [head, ...rest] = u.split('-');
      if (head && rest.length > 0) prefixes.add(head);
    }
  }
  return [...prefixes];
}

function oppositeCasingRegex(prefixes: string[], style: 'camel' | 'kebab'): RegExp | undefined {
  if (prefixes.length === 0) return undefined;
  const alt = prefixes.map((p) => p.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|');
  // If this system is camel-cased, the contamination signature is kebab, and
  // vice versa.
  return style === 'camel'
    ? new RegExp(`\\b(?:${alt})-[a-z][a-z0-9-]*\\b`, 'g')
    : new RegExp(`\\b(?:${alt})[A-Z][A-Za-z0-9]*\\b`, 'g');
}

export function gradeApiFidelity(ctx: GradeContext): DimensionResult {
  const diffs: Diff[] = [];
  let score = 100;
  let requiresFail = false;
  let requiresReview = false;
  let anySystemUsage = false;

  const customElements = ctx.systemCfg.componentModel === 'custom-elements';
  const validExports = new Set(ctx.catalog.allExports);
  const propsTypeNames = new Set(ctx.catalog.allExports.map((e) => `${e}Props`));
  const contaminationProps = new Set(ctx.systemCfg.contamination?.props ?? []);

  const style = ctx.systemCfg.contamination?.typographyStyle;
  const prefixes = style ? typographyPrefixes(ctx.tokens.typographyUtilities, style) : [];
  const contaminationRegex = style ? oppositeCasingRegex(prefixes, style) : undefined;

  for (const file of ctx.files) {
    // Local (per-file) alias -> catalog export name, built from this file's
    // own import statements — aliasing is file-scoped so the map must be too.
    const localToExport = new Map<string, string>();

    for (const imp of file.analysis.imports) {
      if (!matchesPkg(imp.source, ctx.systemCfg.componentsPkg)) continue;
      anySystemUsage = true;

      // Subpath entries (e.g. "<pkg>/icons") are outside what the docgen
      // catalog can enumerate: a subpath barrel may re-export a third-party
      // package wholesale (`export * from 'lucide-react'`), and a bare
      // specifier has no directory for the barrel walk to resolve. Those
      // symbols are real and typecheck, so scoring them as hallucinations
      // punishes correct code. Record them as unverifiable instead - the same
      // treatment member-expression JSX already gets below - and let the
      // compile dimension catch genuinely missing exports.
      if (imp.source !== ctx.systemCfg.componentsPkg) {
        for (const { imported } of imp.names) {
          if (imported === '__default__' || imported === '*') continue;
          if (validExports.has(imported)) continue;
          diffs.push({
            dimension: 'apiFidelity',
            message: `'${imported}' imported from ${imp.source} in ${file.path} - subpath export, not verifiable against the catalog.`,
          });
        }
        continue;
      }

      for (const { imported, local } of imp.names) {
        if (imported === '__default__' || imported === '*') continue; // unverifiable, not tracked

        if (validExports.has(imported)) {
          localToExport.set(local, imported);
          continue;
        }
        if (propsTypeNames.has(imported)) {
          continue; // legitimate `FooProps` type import
        }
        // Not a real export, and not a real `<Export>Props` type either.
        score -= 40;
        requiresFail = true;
        const looksLikeTypeImport = imported.endsWith('Props');
        diffs.push({
          dimension: 'apiFidelity',
          message: looksLikeTypeImport
            ? `Hallucinated type '${imported}' imported from ${ctx.systemCfg.componentsPkg} in ${file.path}`
            : `Hallucinated component '${imported}' imported from ${ctx.systemCfg.componentsPkg} in ${file.path}`,
          fix: `'${imported}' does not exist in the ${ctx.system} catalog. Use one of: ${ctx.catalog.allExports.slice(0, 12).join(', ')}${ctx.catalog.allExports.length > 12 ? ', …' : ''}.`,
        });
      }
    }

    for (const el of file.analysis.jsxElements) {
      // Import-bound name first (both models), then — for a custom-element
      // system only — the tag itself, since those carry no import. See the
      // header for why the dash test is what makes that safe.
      const resolvedTag =
        customElements && el.full.includes('-') && validExports.has(el.full) ? el.full : undefined;
      const resolvedExport = localToExport.get(el.base) ?? resolvedTag;
      if (!resolvedExport) continue; // not a design-system component usage
      if (resolvedTag) anySystemUsage = true;

      if (el.full !== el.base) {
        // Member-expression JSX, e.g. `Modal.Footer` — base already verified
        // above via the import map; sub-component attrs aren't in the
        // docgen catalog at all, so we can't check them.
        diffs.push({
          dimension: 'apiFidelity',
          message: `<${el.full}> in ${file.path}:${el.line} is a sub-component of '${resolvedExport}' — props not verifiable against the catalog.`,
        });
        continue;
      }

      if (el.hasSpread) {
        requiresReview = true;
        diffs.push({
          dimension: 'apiFidelity',
          message: `<${el.full}> in ${file.path}:${el.line} spreads props onto a design-system component — props not statically verifiable.`,
          fix: 'Avoid spreading unknown props onto design-system components when possible.',
        });
        continue;
      }

      const allowedProps = ctx.catalog.allPropsByExport[resolvedExport] ?? [];
      for (const attr of el.attrs) {
        if (isAttrAllowed(attr, allowedProps, customElements)) continue;
        score -= 15;
        requiresReview = true;
        const contamination = contaminationProps.has(attr);
        diffs.push({
          dimension: 'apiFidelity',
          message: `Invented prop '${attr}' on <${el.full}> in ${file.path}:${el.line}${contamination ? ' [cross-system-contamination]' : ''}`,
          fix: `'${attr}' is not a prop of ${resolvedExport}. Valid props: ${allowedProps.join(', ') || '(none)'}.`,
        });
      }
    }

    if (contaminationRegex) {
      for (const cls of file.analysis.classNameLiterals) {
        contaminationRegex.lastIndex = 0;
        let match: RegExpExecArray | null;
        while ((match = contaminationRegex.exec(cls.value))) {
          score -= 10;
          requiresReview = true;
          diffs.push({
            dimension: 'apiFidelity',
            message: `Class '${match[0]}' in ${file.path}:${cls.line} uses another system's typography-utility casing (this system is ${style}) [cross-system-contamination]`,
            fix: `Use this system's ${style}-cased typography utilities (e.g. ${ctx.tokens.typographyUtilities[0] ?? ''}).`,
          });
        }
      }
    }
  }

  if (!anySystemUsage) {
    // "Ignored the design system" is a first-class failure, not a neutral
    // outcome: output that avoids the system passes every other API gate
    // while being the worst result a design-system team can get.
    return {
      dimension: 'apiFidelity',
      score: 0,
      gate: 'fail',
      diffs: [{ dimension: 'apiFidelity', message: 'no design-system components used' }],
    };
  }

  score = Math.max(0, Math.min(100, score));
  const gate: Gate = requiresFail ? 'fail' : requiresReview ? 'review' : 'pass';

  return { dimension: 'apiFidelity', score, gate, diffs };
}
